### ISSUE TITLE
회원가입

### ISSUE THREAD

**Issue by dydwo0740** [Yummy-Trip/YummyTrip-Backend#1]
## Description

Spring Security를 기반으로 하여, 회원가입 로직을 작성합니다.

## Todo

* [x] SecurityConfiguerer 설정합니다.
* [x] enum으로 사용자 인가 설정합니다.
* [x] JWT토큰을 활용합니다.
* [x] 회원가입 사용자 정보 controller 구현합니다. 
* [x] 회원가입 service를 구현합니다.
    * [x] 이미 등록된 이메일인 경우 exception 을 발생시킵니다.
* [x] mybatis를 활용하여 회원가입 mapper 구현합니다.
